### ISSUE TITLE
請問Model有用到QA或NLI的dataset進行訓練嗎?

### ISSUE THREAD

**Issue by ianyang66** [ymcui/LERT#2]

**Comment by ymcui** [comment]
我理解你应该是问预训练过程是否使用QA/NLI数据是吧？
预训练过程中，
1、没有使用任何带标注数据（包括QA或NLI等）
2、预训练数据中可能会包含问答类数据（例如社区问答等），但和其他领域的数据一样，都是以无标注数据的形式进行训练的，并非针对这些任务进行特定适配。
