### ISSUE TITLE
TensorFlow 1.x版本的模型参数加载失败

### ISSUE THREAD

**Issue by 600DZY** [ymcui/LERT#6]
下载TensorFlow 1.x版本的模型参数后，通过tf加载出现如下报错： Unsuccessful TensorSliceReader constructor: Failed to find any matching files for  xxx/lert_base_tf/lert_mode.ckpt。在windows和linux平台下对base和small版本的模型参数进行加载测试均未成功，但相同代码能够成功加载MacBert模型，甚是疑惑，希望能够得到解答，测试代码如下：

checkpoint='/xxx/lert_base_tf/lert_mode.ckpt'
name='bert/embeddings/word_embeddings'
tf.train.load_variable(checkpoint, name)
#init_vars = tf.train.list_variables(checkpoint)

**Comment by ymcui** [comment]
检查一下文件名是否正确？ 你这里加载的是`lert_mode.ckpt`

**Comment by 600DZY** [comment]
（1）lert_config_base.json（2）lert_model.ckpt.data-00000-of-00001（3）lert_model.ckpt.index（4）lert_model.ckpt.meta（5）vocab.txt，  解压的文件就这些，类似的文件格式，我用“chinese_macbert_base.ckpt”这个文件名是可以加载到的

**Comment by ymcui** [comment]
是，但是你在问题中写的是`lert_mode.ckpt`不是`lert_model.ckpt`，所以和你确认是不是文件名写错了。

**Comment by 600DZY** [comment]
真的写错了！！
